/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.Projeto.view;

/**
 *
 * @author silva
 */
public class Telas extends javax.swing.JFrame {

    /**
     * Creates new form Telas
     */
    public Telas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btProduto = new javax.swing.JButton();
        btCliente = new javax.swing.JButton();
        btGerenciamento = new javax.swing.JButton();
        btUsuario = new javax.swing.JButton();
        btVenda = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btProduto.setBackground(new java.awt.Color(204, 204, 204));
        btProduto.setForeground(new java.awt.Color(0, 0, 0));
        btProduto.setText("Produto");
        btProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btProdutoMouseClicked(evt);
            }
        });
        getContentPane().add(btProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 145, 215, 43));

        btCliente.setBackground(new java.awt.Color(204, 204, 204));
        btCliente.setForeground(new java.awt.Color(0, 0, 0));
        btCliente.setText("Cliente");
        btCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btClienteMouseClicked(evt);
            }
        });
        getContentPane().add(btCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 205, 215, 45));

        btGerenciamento.setBackground(new java.awt.Color(204, 204, 204));
        btGerenciamento.setForeground(new java.awt.Color(0, 0, 0));
        btGerenciamento.setText("Gerencia");
        btGerenciamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btGerenciamentoMouseClicked(evt);
            }
        });
        getContentPane().add(btGerenciamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 215, 45));

        btUsuario.setBackground(new java.awt.Color(204, 204, 204));
        btUsuario.setForeground(new java.awt.Color(0, 0, 0));
        btUsuario.setText("Usuário");
        btUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btUsuarioMouseClicked(evt);
            }
        });
        getContentPane().add(btUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, 215, 45));

        btVenda.setBackground(new java.awt.Color(204, 204, 204));
        btVenda.setForeground(new java.awt.Color(0, 0, 0));
        btVenda.setText("Venda");
        btVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btVendaMouseClicked(evt);
            }
        });
        getContentPane().add(btVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 265, 215, 45));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Projeto/imagens/TELA INICIAL.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btProdutoMouseClicked
        TelaProduto pro = new TelaProduto();
        pro.setVisible(true);
    }//GEN-LAST:event_btProdutoMouseClicked

    private void btClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btClienteMouseClicked
        TelaCliente cli = new TelaCliente();
        cli.setVisible(true);
    }//GEN-LAST:event_btClienteMouseClicked

    private void btVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btVendaMouseClicked
        TelaVenda vend = new TelaVenda();
        vend.setVisible(true);
    }//GEN-LAST:event_btVendaMouseClicked

    private void btGerenciamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btGerenciamentoMouseClicked
        Gerenciamento g = new Gerenciamento();
        g.setVisible(true);
    }//GEN-LAST:event_btGerenciamentoMouseClicked

    private void btUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btUsuarioMouseClicked
        TelaUsuario user = new TelaUsuario();
        user.setVisible(true);
    }//GEN-LAST:event_btUsuarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Telas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Telas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Telas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Telas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Telas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCliente;
    private javax.swing.JButton btGerenciamento;
    private javax.swing.JButton btProduto;
    private javax.swing.JButton btUsuario;
    private javax.swing.JButton btVenda;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
