/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.Projeto.view;

import br.com.Projeto.model.Usuario;
import br.com.Projeto.dao.UsuarioDao;




public class TelaUsuario extends javax.swing.JFrame {

    /**
     * Creates new form Usuario
     */
    public TelaUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtConfirmarsenha = new javax.swing.JPasswordField();
        txtSenhaa = new javax.swing.JPasswordField();
        txtSobrenome = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        btProduto = new javax.swing.JButton();
        btCliente = new javax.swing.JButton();
        btVenda = new javax.swing.JButton();
        btGerenciamento = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        btUsuario = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtConfirmarsenha.setBackground(new java.awt.Color(204, 204, 204));
        txtConfirmarsenha.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtConfirmarsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 282, 170, 33));

        txtSenhaa.setBackground(new java.awt.Color(204, 204, 204));
        txtSenhaa.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtSenhaa, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 242, 170, 34));

        txtSobrenome.setBackground(new java.awt.Color(204, 204, 204));
        txtSobrenome.setForeground(new java.awt.Color(0, 0, 0));
        txtSobrenome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSobrenomeActionPerformed(evt);
            }
        });
        getContentPane().add(txtSobrenome, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 168, 210, 33));

        jTextField3.setText("jTextField1");
        getContentPane().add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(263, 127, 71, 0));

        jTextField4.setText("jTextField1");
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 137, 71, 0));

        txtEmail.setBackground(new java.awt.Color(204, 204, 204));
        txtEmail.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 205, 370, 33));

        txtNome.setBackground(new java.awt.Color(204, 204, 204));
        txtNome.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 128, 210, 32));

        btProduto.setBackground(new java.awt.Color(204, 204, 204));
        btProduto.setForeground(new java.awt.Color(0, 0, 0));
        btProduto.setText("Produto");
        btProduto.setToolTipText("Produto");
        btProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btProdutoMouseClicked(evt);
            }
        });
        getContentPane().add(btProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 50, -1));

        btCliente.setBackground(new java.awt.Color(204, 204, 204));
        btCliente.setForeground(new java.awt.Color(0, 0, 0));
        btCliente.setText("Cliente");
        btCliente.setToolTipText("Cliente");
        btCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btClienteMouseClicked(evt);
            }
        });
        getContentPane().add(btCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 118, 50, -1));

        btVenda.setBackground(new java.awt.Color(204, 204, 204));
        btVenda.setForeground(new java.awt.Color(0, 0, 0));
        btVenda.setText("Venda");
        btVenda.setToolTipText("Venda");
        btVenda.setOpaque(true);
        btVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btVendaMouseClicked(evt);
            }
        });
        getContentPane().add(btVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 145, 50, 25));

        btGerenciamento.setBackground(new java.awt.Color(204, 204, 204));
        btGerenciamento.setForeground(new java.awt.Color(0, 0, 0));
        btGerenciamento.setText("Gerenciamento");
        btGerenciamento.setToolTipText("Gerenciamento");
        btGerenciamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btGerenciamentoMouseClicked(evt);
            }
        });
        getContentPane().add(btGerenciamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 205, 50, 27));

        jButton6.setBackground(new java.awt.Color(204, 204, 204));
        jButton6.setForeground(new java.awt.Color(0, 0, 0));
        jButton6.setText("Usuário");
        jButton6.setToolTipText("Usuário");
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 235, 50, 27));

        btUsuario.setBackground(new java.awt.Color(204, 204, 204));
        btUsuario.setForeground(new java.awt.Color(0, 0, 0));
        btUsuario.setText("SALVAR");
        btUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(btUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 170, 40));

        jButton5.setBackground(new java.awt.Color(204, 204, 204));
        jButton5.setForeground(new java.awt.Color(0, 0, 0));
        jButton5.setText("EXCLUIR");
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, 170, 40));

        jButton7.setBackground(new java.awt.Color(204, 204, 204));
        jButton7.setForeground(new java.awt.Color(0, 0, 0));
        jButton7.setText("EDITAR");
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 400, 170, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Projeto/imagens/Usuário.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSobrenomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSobrenomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSobrenomeActionPerformed

    private void btUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUsuarioActionPerformed
         Usuario use = new Usuario();
        
        use.setNome((txtNome.getText()));
        use.setSobrenome(txtSobrenome.getText());
        use.setEmail(txtEmail.getText());
        use.setSenha(txtSenhaa.getText());
        use.setConfirmarsenha(txtConfirmarsenha.getText());
        
        UsuarioDao dao = new UsuarioDao();
        dao.salvarUsuario(use);
        
        
        
        
    }//GEN-LAST:event_btUsuarioActionPerformed

    private void btProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btProdutoMouseClicked
        TelaProduto pro = new TelaProduto();
        pro.setVisible(true);
    }//GEN-LAST:event_btProdutoMouseClicked

    private void btClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btClienteMouseClicked
        TelaCliente cli = new TelaCliente();
        cli.setVisible(true);
    }//GEN-LAST:event_btClienteMouseClicked

    private void btVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btVendaMouseClicked
          TelaVenda vend = new TelaVenda();
        vend.setVisible(true);
    }//GEN-LAST:event_btVendaMouseClicked

    private void btGerenciamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btGerenciamentoMouseClicked
         Gerenciamento g = new Gerenciamento();
        g.setVisible(true);
    }//GEN-LAST:event_btGerenciamentoMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCliente;
    private javax.swing.JButton btGerenciamento;
    private javax.swing.JButton btProduto;
    private javax.swing.JButton btUsuario;
    private javax.swing.JButton btVenda;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JPasswordField txtConfirmarsenha;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtSenhaa;
    private javax.swing.JTextField txtSobrenome;
    // End of variables declaration//GEN-END:variables

    
}
