/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */ 
package br.com.Projeto.view;

import br.com.Projeto.dao.VendaDao;
import br.com.Projeto.model.Venda;

/**
 *
 * @author silva
 */
public class TelaVenda extends javax.swing.JFrame {

    /**
     * Creates new form Venda
     */
    public TelaVenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btProduto = new javax.swing.JButton();
        btVenda = new javax.swing.JButton();
        btCliente = new javax.swing.JButton();
        btGerenciamento = new javax.swing.JButton();
        btUsuario = new javax.swing.JButton();
        Salvar = new javax.swing.JButton();
        Excluir = new javax.swing.JButton();
        cbSaborr = new javax.swing.JComboBox<>();
        cbTipo = new javax.swing.JComboBox<>();
        txtPagamento = new javax.swing.JFormattedTextField();
        txtData = new javax.swing.JFormattedTextField();
        txtQuantidade = new javax.swing.JTextField();
        txtCliente = new javax.swing.JTextField();
        Editar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btProduto.setBackground(new java.awt.Color(204, 204, 204));
        btProduto.setForeground(new java.awt.Color(0, 0, 0));
        btProduto.setText("Produto");
        btProduto.setToolTipText("Produto");
        btProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btProdutoMouseClicked(evt);
            }
        });
        getContentPane().add(btProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 50, -1));

        btVenda.setBackground(new java.awt.Color(204, 204, 204));
        btVenda.setForeground(new java.awt.Color(0, 0, 0));
        btVenda.setText("Venda");
        btVenda.setToolTipText("Venda");
        btVenda.setOpaque(true);
        btVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btVendaMouseClicked(evt);
            }
        });
        getContentPane().add(btVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 145, 50, 23));

        btCliente.setBackground(new java.awt.Color(204, 204, 204));
        btCliente.setForeground(new java.awt.Color(0, 0, 0));
        btCliente.setText("Cliente");
        btCliente.setToolTipText("Cliente");
        btCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btClienteMouseClicked(evt);
            }
        });
        getContentPane().add(btCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 117, 50, -1));

        btGerenciamento.setBackground(new java.awt.Color(204, 204, 204));
        btGerenciamento.setForeground(new java.awt.Color(0, 0, 0));
        btGerenciamento.setText("Gerenciamento");
        btGerenciamento.setToolTipText("Gerenciamento");
        btGerenciamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btGerenciamentoMouseClicked(evt);
            }
        });
        getContentPane().add(btGerenciamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 205, 50, 25));

        btUsuario.setBackground(new java.awt.Color(204, 204, 204));
        btUsuario.setForeground(new java.awt.Color(0, 0, 0));
        btUsuario.setText("Usuário");
        btUsuario.setToolTipText("Usuário");
        btUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btUsuarioMouseClicked(evt);
            }
        });
        getContentPane().add(btUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 235, 50, 25));

        Salvar.setBackground(new java.awt.Color(204, 204, 204));
        Salvar.setForeground(new java.awt.Color(0, 0, 0));
        Salvar.setText("SALVAR");
        Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarActionPerformed(evt);
            }
        });
        getContentPane().add(Salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 175, 40));

        Excluir.setBackground(new java.awt.Color(204, 204, 204));
        Excluir.setForeground(new java.awt.Color(0, 0, 0));
        Excluir.setText("EXCLUIR");
        Excluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExcluirMouseClicked(evt);
            }
        });
        Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(Excluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 400, 170, 40));

        cbSaborr.setBackground(new java.awt.Color(102, 102, 102));
        cbSaborr.setForeground(new java.awt.Color(0, 0, 0));
        cbSaborr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Maracuja", "Acerola", "Caju" }));
        cbSaborr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSaborrActionPerformed(evt);
            }
        });
        getContentPane().add(cbSaborr, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 152, 113, 33));

        cbTipo.setBackground(new java.awt.Color(102, 102, 102));
        cbTipo.setForeground(new java.awt.Color(0, 0, 0));
        cbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Cartão", "Pix", "A vista" }));
        getContentPane().add(cbTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 303, 115, 30));

        txtPagamento.setBackground(new java.awt.Color(204, 204, 204));
        txtPagamento.setForeground(new java.awt.Color(0, 0, 0));
        try {
            txtPagamento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("R$###,##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txtPagamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 264, 154, 30));

        txtData.setBackground(new java.awt.Color(204, 204, 204));
        txtData.setForeground(new java.awt.Color(0, 0, 0));
        try {
            txtData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txtData, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 227, 154, 30));

        txtQuantidade.setBackground(new java.awt.Color(204, 204, 204));
        txtQuantidade.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 90, 30));

        txtCliente.setBackground(new java.awt.Color(204, 204, 204));
        txtCliente.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 117, 325, 30));

        Editar.setBackground(new java.awt.Color(204, 204, 204));
        Editar.setForeground(new java.awt.Color(0, 0, 0));
        Editar.setText("EDITAR");
        Editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditarMouseClicked(evt);
            }
        });
        getContentPane().add(Editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 180, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Projeto/imagens/Tela 3.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbSaborrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSaborrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbSaborrActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarActionPerformed
           Venda vend = new Venda();
               
        vend.setCliente(txtCliente.getText());
        vend.setProduto(cbSaborr.getSelectedItem().toString());
        vend.setQuantidade(Integer.parseInt(txtQuantidade.getText()));
        vend.setDat(txtData.getText());
        vend.setPagamento(txtPagamento.getText());
        vend.setTipopagamento(cbTipo.getSelectedItem().toString());
        
         
        VendaDao dao = new VendaDao();
        dao.salvarVenda(vend);
    }//GEN-LAST:event_SalvarActionPerformed

    private void ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirActionPerformed
        // TODO add your handling code here:
          Venda vend = new Venda();
        vend.setCliente(txtCliente.getText());
        
        VendaDao dao = new VendaDao();
        dao.excluirVenda(vend);
    }//GEN-LAST:event_ExcluirActionPerformed

    private void EditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarMouseClicked
        // TODO add your handling code here:
        Venda vend = new Venda();
        
        
        vend.setCliente(txtCliente.getText());
        vend.setProduto(cbSaborr.getSelectedItem().toString());
        vend.setQuantidade(Integer.parseInt(txtQuantidade.getText()));
        vend.setDat(txtData.getText());
        vend.setPagamento(txtPagamento.getText());
        vend.setTipopagamento(cbTipo.getSelectedItem().toString());
        
         
         
        VendaDao dao = new VendaDao();
        dao.editarVenda(vend);
    }//GEN-LAST:event_EditarMouseClicked

    private void ExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExcluirMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ExcluirMouseClicked

    private void btProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btProdutoMouseClicked
        TelaProduto pro = new TelaProduto();
        pro.setVisible(true);
    }//GEN-LAST:event_btProdutoMouseClicked

    private void btClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btClienteMouseClicked
        TelaCliente cli = new TelaCliente();
        cli.setVisible(true);
    }//GEN-LAST:event_btClienteMouseClicked

    private void btVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btVendaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btVendaMouseClicked

    private void btGerenciamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btGerenciamentoMouseClicked
        Gerenciamento g = new Gerenciamento();
        g.setVisible(true);
    }//GEN-LAST:event_btGerenciamentoMouseClicked

    private void btUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btUsuarioMouseClicked
        TelaUsuario user = new TelaUsuario();
        user.setVisible(true);
    }//GEN-LAST:event_btUsuarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaVenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaVenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Editar;
    private javax.swing.JButton Excluir;
    private javax.swing.JButton Salvar;
    private javax.swing.JButton btCliente;
    private javax.swing.JButton btGerenciamento;
    private javax.swing.JButton btProduto;
    private javax.swing.JButton btUsuario;
    private javax.swing.JButton btVenda;
    public javax.swing.JComboBox<String> cbSaborr;
    public javax.swing.JComboBox<String> cbTipo;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JTextField txtCliente;
    public javax.swing.JFormattedTextField txtData;
    public javax.swing.JFormattedTextField txtPagamento;
    public javax.swing.JTextField txtQuantidade;
    // End of variables declaration//GEN-END:variables
}
