/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.Projeto.view;

import br.com.Projeto.dao.ClienteDao;
import br.com.Projeto.model.Cliente;

public class TelaCliente extends javax.swing.JFrame {

    
    

  
    /**
     * Creates new form Cliente
     */
    public TelaCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        btGerenciamento = new javax.swing.JButton();
        btVenda = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        btProduto = new javax.swing.JButton();
        Excluir = new javax.swing.JButton();
        btUsuario = new javax.swing.JButton();
        Salvar = new javax.swing.JButton();
        txtCelular = new javax.swing.JFormattedTextField();
        txtCpf = new javax.swing.JFormattedTextField();
        txtNascimento = new javax.swing.JFormattedTextField();
        txtName = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtEndereco = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        txtComplemento = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        cbEstado = new javax.swing.JComboBox<>();
        Editar = new javax.swing.JButton();
        JLabel = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();

        jTextField2.setText("jTextField2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btGerenciamento.setBackground(new java.awt.Color(204, 204, 204));
        btGerenciamento.setForeground(new java.awt.Color(0, 0, 0));
        btGerenciamento.setText("Gerenciamento");
        btGerenciamento.setToolTipText("Gerenciamento");
        btGerenciamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btGerenciamentoMouseClicked(evt);
            }
        });
        getContentPane().add(btGerenciamento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 198, 50, 25));

        btVenda.setBackground(new java.awt.Color(204, 204, 204));
        btVenda.setForeground(new java.awt.Color(0, 0, 0));
        btVenda.setText("Venda");
        btVenda.setToolTipText("Venda");
        btVenda.setOpaque(true);
        btVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btVendaMouseClicked(evt);
            }
        });
        btVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVendaActionPerformed(evt);
            }
        });
        getContentPane().add(btVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 132, 50, -1));

        jButton3.setBackground(new java.awt.Color(204, 204, 204));
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Cliente");
        jButton3.setToolTipText("Cliente");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 106, 50, -1));

        btProduto.setBackground(new java.awt.Color(204, 204, 204));
        btProduto.setForeground(new java.awt.Color(0, 0, 0));
        btProduto.setText("Produto");
        btProduto.setToolTipText("Produto");
        btProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btProdutoMouseClicked(evt);
            }
        });
        getContentPane().add(btProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 50, -1));

        Excluir.setBackground(new java.awt.Color(204, 204, 204));
        Excluir.setForeground(new java.awt.Color(0, 0, 0));
        Excluir.setText("EXCLUIR");
        Excluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExcluirMouseClicked(evt);
            }
        });
        Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(Excluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, 160, 40));

        btUsuario.setBackground(new java.awt.Color(204, 204, 204));
        btUsuario.setForeground(new java.awt.Color(0, 0, 0));
        btUsuario.setText("Usuário");
        btUsuario.setToolTipText("Usuário");
        btUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btUsuarioMouseClicked(evt);
            }
        });
        btUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(btUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 225, 50, -1));

        Salvar.setBackground(new java.awt.Color(204, 204, 204));
        Salvar.setForeground(new java.awt.Color(0, 0, 0));
        Salvar.setText("SALVAR");
        Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarActionPerformed(evt);
            }
        });
        getContentPane().add(Salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, 165, 40));

        txtCelular.setBackground(new java.awt.Color(204, 204, 204));
        txtCelular.setForeground(new java.awt.Color(0, 0, 0));
        try {
            txtCelular.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txtCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 235, 132, 30));

        txtCpf.setBackground(new java.awt.Color(204, 204, 204));
        txtCpf.setForeground(new java.awt.Color(0, 0, 0));
        try {
            txtCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(txtCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 202, 132, 30));

        txtNascimento.setBackground(new java.awt.Color(204, 204, 204));
        txtNascimento.setForeground(new java.awt.Color(0, 0, 0));
        try {
            txtNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNascimentoActionPerformed(evt);
            }
        });
        getContentPane().add(txtNascimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 141, 140, 26));

        txtName.setBackground(new java.awt.Color(204, 204, 204));
        txtName.setForeground(new java.awt.Color(0, 0, 0));
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        getContentPane().add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 106, 180, 30));

        txtEmail.setBackground(new java.awt.Color(204, 204, 204));
        txtEmail.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(203, 170, 186, 30));

        txtEndereco.setBackground(new java.awt.Color(204, 204, 204));
        txtEndereco.setForeground(new java.awt.Color(0, 0, 0));
        txtEndereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEnderecoActionPerformed(evt);
            }
        });
        getContentPane().add(txtEndereco, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 97, 162, 27));

        txtNumero.setBackground(new java.awt.Color(204, 204, 204));
        txtNumero.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 130, 60, 30));

        txtBairro.setBackground(new java.awt.Color(204, 204, 204));
        txtBairro.setForeground(new java.awt.Color(0, 0, 0));
        txtBairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBairroActionPerformed(evt);
            }
        });
        getContentPane().add(txtBairro, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 161, 145, 30));

        txtComplemento.setBackground(new java.awt.Color(204, 204, 204));
        txtComplemento.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtComplemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 226, 160, 30));

        txtCidade.setBackground(new java.awt.Color(204, 204, 204));
        txtCidade.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(txtCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 194, 160, 30));

        cbEstado.setBackground(new java.awt.Color(102, 102, 102));
        cbEstado.setForeground(new java.awt.Color(0, 0, 0));
        cbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        cbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbEstadoActionPerformed(evt);
            }
        });
        getContentPane().add(cbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 260, 80, 30));

        Editar.setBackground(new java.awt.Color(204, 204, 204));
        Editar.setForeground(new java.awt.Color(0, 0, 0));
        Editar.setText("EDITAR");
        Editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditarMouseClicked(evt);
            }
        });
        getContentPane().add(Editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 170, 40));

        JLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/Projeto/imagens/Tela 2 (2).png"))); // NOI18N
        JLabel.setText("jLabel1");
        getContentPane().add(JLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 720, -1));
        getContentPane().add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNascimentoActionPerformed

    private void btUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btUsuarioActionPerformed

    private void SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarActionPerformed

        Cliente cliente = new Cliente();
        
        cliente.setNome(txtName.getText());
        cliente.setNascimento(txtNascimento.getText());
        cliente.setEmail(txtEmail.getText());
        cliente.setCpf(txtCpf.getText());
        cliente.setEndereco(txtEndereco.getText());
        cliente.setNumero(Integer.parseInt(txtNumero.getText()));
        cliente.setBairro(txtBairro.getText());
        cliente.setCelular(txtCelular.getText());
        cliente.setComplemento(txtComplemento.getText());
        cliente.setCidade(txtCidade.getText());
        cliente.setEstado(cbEstado.getSelectedItem().toString());
        
        
        ClienteDao dao = new ClienteDao();
        dao.salvarCliente(cliente);
    }//GEN-LAST:event_SalvarActionPerformed

    private void cbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbEstadoActionPerformed

    private void txtBairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBairroActionPerformed

    private void btVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btVendaActionPerformed

    private void txtEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEnderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEnderecoActionPerformed

    private void EditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarMouseClicked
        // TODO add your handling code here:
        Cliente cliente = new Cliente();
        
        cliente.setNome(txtName.getText());
        cliente.setNascimento(txtNascimento.getText());
        cliente.setEmail(txtEmail.getText());
        cliente.setCpf(txtCpf.getText());
        cliente.setEndereco(txtEndereco.getText());
        cliente.setNumero(Integer.parseInt(txtNumero.getText()));
        cliente.setBairro(txtBairro.getText());
        cliente.setCelular(txtCelular.getText());
        cliente.setComplemento(txtComplemento.getText());
        cliente.setCidade(txtCidade.getText());
        cliente.setEstado(cbEstado.getSelectedItem().toString());
         
        
        ClienteDao dao = new ClienteDao();
        dao.editarCliente(cliente);
    }//GEN-LAST:event_EditarMouseClicked

    private void ExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExcluirMouseClicked
        // TODO add your handling code here:
        Cliente cliente = new Cliente();
        
        cliente.setCpf(txtCpf.getText());
        
        ClienteDao dao = new ClienteDao();
        dao.excluirCliente(cliente);
        
          
    }//GEN-LAST:event_ExcluirMouseClicked

    private void ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExcluirActionPerformed

    private void btProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btProdutoMouseClicked
         TelaProduto pro = new TelaProduto();
        pro.setVisible(true);
    }//GEN-LAST:event_btProdutoMouseClicked

    private void btVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btVendaMouseClicked
        TelaVenda vend = new TelaVenda();
        vend.setVisible(true);
    }//GEN-LAST:event_btVendaMouseClicked

    private void btGerenciamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btGerenciamentoMouseClicked
         Gerenciamento g = new Gerenciamento();
        g.setVisible(true);
    }//GEN-LAST:event_btGerenciamentoMouseClicked

    private void btUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btUsuarioMouseClicked
          TelaUsuario user = new TelaUsuario();
        user.setVisible(true);
    }//GEN-LAST:event_btUsuarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Editar;
    private javax.swing.JButton Excluir;
    private javax.swing.JLabel JLabel;
    private javax.swing.JButton Salvar;
    private javax.swing.JButton btGerenciamento;
    private javax.swing.JButton btProduto;
    private javax.swing.JButton btUsuario;
    private javax.swing.JButton btVenda;
    public javax.swing.JComboBox<String> cbEstado;
    private javax.swing.JButton jButton3;
    private javax.swing.JTextField jTextField2;
    public javax.swing.JTextField txtBairro;
    public javax.swing.JFormattedTextField txtCelular;
    public javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtCodigo;
    public javax.swing.JTextField txtComplemento;
    public javax.swing.JFormattedTextField txtCpf;
    public javax.swing.JTextField txtEmail;
    public javax.swing.JTextField txtEndereco;
    public javax.swing.JTextField txtName;
    public javax.swing.JFormattedTextField txtNascimento;
    public javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables


}
